<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Audit Logs Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'DejaVu Sans', Arial, Helvetica, sans-serif;
            font-size: 10px;
            color: #333;
            line-height: 1.4;
            margin-left: 30px;
            margin-right: 30px;
        }
        
        .header {
            background: linear-gradient(135deg, #055498 0%, #123a60 100%);
            color: #000000 !important;
            padding: 20px;
            margin-bottom: 10px;
            border-radius: 5px;
            text-align: center;
        }
        
        .header img {
            max-width: 400px;
            height: auto;
            margin-top: 10px;
            margin-bottom: 10px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
        
        .header h1 {
            font-size: 24px;
            margin-bottom: 5px;
            margin-top: 5px;
            font-weight: bold;
            color: #000000 !important;
        }
        
        .header p {
            font-size: 11px;
            opacity: 1;
            margin-bottom: 5px;
            color: #000000 !important;
        }
        
        .info-section {
            background-color: #f8f9fa;
            padding: 15px;
            margin-top: 5px;
            margin-bottom: 20px;
            border-radius: 5px;
            border-left: 4px solid #055498;
        }
        
        .info-row {
            display: table;
            width: 100%;
            margin-bottom: 8px;
        }
        
        .info-label {
            display: table-cell;
            font-weight: bold;
            width: 150px;
            color: #555;
        }
        
        .info-value {
            display: table-cell;
            color: #333;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            background-color: white;
        }
        
        thead {
            background-color: #055498;
            color: white;
        }
        
        thead th {
            padding: 10px 8px;
            text-align: left;
            font-weight: bold;
            font-size: 9px;
            text-transform: uppercase;
            border: 1px solid #044080;
        }
        
        tbody td {
            padding: 8px;
            border: 1px solid #e0e0e0;
            font-size: 9px;
        }
        
        tbody tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        
        tbody tr:hover {
            background-color: #e8f4f8;
        }
        
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 8px;
            font-weight: bold;
            background-color: rgba(5, 84, 152, 0.1);
            color: #055498;
        }
        
        .user-name {
            font-weight: bold;
            color: #333;
        }
        
        .user-email {
            font-size: 8px;
            color: #666;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #e0e0e0;
            text-align: center;
            color: #666;
            font-size: 9px;
        }
        
        .page-break {
            page-break-after: always;
        }
        
        .text-center {
            text-align: center;
        }
        
        .text-right {
            text-align: right;
        }
        
        .no-data {
            padding: 30px;
            text-align: center;
            color: #999;
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('images/ddbheader.png') }}" alt="DDB Header">
        <h1>Audit Logs Report</h1>
        <p>System-wide user activity trail</p>
    </div>
    
    <div class="info-section">
        <div class="info-row">
            <div class="info-label">Generated On:</div>
            <div class="info-value">{{ now()->format('F d, Y h:i A') }}</div>
        </div>
        <div class="info-row">
            <div class="info-label">Generated By:</div>
            <div class="info-value">{{ Auth::user()->first_name }} {{ Auth::user()->last_name }} ({{ Auth::user()->email }})</div>
        </div>
        <div class="info-row">
            <div class="info-label">Total Records:</div>
            <div class="info-value">{{ $logs->count() }}</div>
        </div>
    </div>
    
    @if($logs->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 12%;">Date / Time</th>
                    <th style="width: 15%;">User</th>
                    <th style="width: 12%;">Action</th>
                    <th style="width: 25%;">Description</th>
                    <th style="width: 10%;">IP Address</th>
                    <th style="width: 13%;">Route / Method</th>
                    <th style="width: 13%;">Model</th>
                </tr>
            </thead>
            <tbody>
                @foreach($logs as $log)
                    <tr>
                        <td>
                            {{ $log->created_at?->format('M d, Y') }}<br>
                            <span style="color: #666; font-size: 8px;">{{ $log->created_at?->format('h:i A') }}</span>
                        </td>
                        <td>
                            @if($log->user)
                                <div class="user-name">{{ $log->user->first_name }} {{ $log->user->last_name }}</div>
                                <div class="user-email">{{ $log->user->email }}</div>
                            @else
                                <span style="color: #999;">System / Guest</span>
                            @endif
                        </td>
                        <td>
                            <span class="badge">{{ $log->action }}</span>
                        </td>
                        <td>
                            {{ $log->description ?? '—' }}
                        </td>
                        <td>
                            {{ $log->ip_address ?? '—' }}
                        </td>
                        <td>
                            <div style="font-weight: bold; font-size: 8px; color: #055498;">{{ $log->method ?? '—' }}</div>
                            @php
                                $url = $log->url ?? '';
                                $path = parse_url($url, PHP_URL_PATH);
                                $query = parse_url($url, PHP_URL_QUERY);
                                $displayUrl = $path ?? $url;
                                if ($query) {
                                    $displayUrl .= '?' . $query;
                                }
                            @endphp
                            <div style="font-size: 8px; color: #666; word-break: break-all;">{{ \Illuminate\Support\Str::limit($displayUrl, 40) }}</div>
                        </td>
                        <td>
                            @if($log->model_type)
                                <div style="font-weight: bold; color: #333;">{{ class_basename($log->model_type) }}</div>
                            @else
                                <span style="color: #999;">—</span>
                            @endif
                            @if($log->model_id)
                                <div style="font-size: 8px; color: #666;">ID: {{ $log->model_id }}</div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No audit logs found.</p>
        </div>
    @endif
    
    <div class="footer">
        <p>This report was generated on {{ now()->format('F d, Y \a\t h:i A') }} from the Board Member Portal System</p>
    </div>
</body>
</html>

